import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const listItems=[
    {
      name: "Projects",
      link: "/projects"
    },
    {
      name: "Hobbies",
      link: "/hobbies",
    },
    {
      name: "Contact Me",
      link: "/contact_me"
    }
  ]

  const companyName = 'ABCHUNG'
  return (
    <html lang="en">
      <body>
        <Navbar listItems={listItems} companyName={companyName}/>
        {children}
      </body>
    </html>
  );
}
